CREATE TABLE `one_page_wpusermeta` (  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `user_id` bigint(20) unsigned NOT NULL DEFAULT 0,  `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,  `meta_value` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,  PRIMARY KEY (`umeta_id`),  KEY `user_id` (`user_id`),  KEY `meta_key` (`meta_key`(191))) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `one_page_wpusermeta` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `one_page_wpusermeta` VALUES('1', '1', 'nickname', 'shwuchin123');
INSERT INTO `one_page_wpusermeta` VALUES('2', '1', 'first_name', '');
INSERT INTO `one_page_wpusermeta` VALUES('3', '1', 'last_name', '');
INSERT INTO `one_page_wpusermeta` VALUES('4', '1', 'description', '');
INSERT INTO `one_page_wpusermeta` VALUES('5', '1', 'rich_editing', 'true');
INSERT INTO `one_page_wpusermeta` VALUES('6', '1', 'syntax_highlighting', 'true');
INSERT INTO `one_page_wpusermeta` VALUES('7', '1', 'comment_shortcuts', 'false');
INSERT INTO `one_page_wpusermeta` VALUES('8', '1', 'admin_color', 'midnight');
INSERT INTO `one_page_wpusermeta` VALUES('9', '1', 'use_ssl', '0');
INSERT INTO `one_page_wpusermeta` VALUES('10', '1', 'show_admin_bar_front', 'true');
INSERT INTO `one_page_wpusermeta` VALUES('11', '1', 'locale', '');
INSERT INTO `one_page_wpusermeta` VALUES('12', '1', 'one_page_wpcapabilities', 'a:1:{s:13:\"administrator\";b:1;}');
INSERT INTO `one_page_wpusermeta` VALUES('13', '1', 'one_page_wpuser_level', '10');
INSERT INTO `one_page_wpusermeta` VALUES('14', '1', 'dismissed_wp_pointers', 'theme_editor_notice');
INSERT INTO `one_page_wpusermeta` VALUES('15', '1', 'show_welcome_panel', '1');
INSERT INTO `one_page_wpusermeta` VALUES('17', '1', 'one_page_wpdashboard_quick_press_last_post_id', '492');
INSERT INTO `one_page_wpusermeta` VALUES('18', '1', 'one_page_wpuser-settings', 'libraryContent=browse&editor=tinymce&hidetb=1&editor_plain_text_paste_warning=1');
INSERT INTO `one_page_wpusermeta` VALUES('19', '1', 'one_page_wpuser-settings-time', '1589473743');
INSERT INTO `one_page_wpusermeta` VALUES('20', '1', 'tgmpa_dismissed_notice_meilleur-business', '1');
INSERT INTO `one_page_wpusermeta` VALUES('21', '1', 'nav_menu_recently_edited', '3');
INSERT INTO `one_page_wpusermeta` VALUES('22', '1', 'managenav-menuscolumnshidden', 'a:5:{i:0;s:11:\"link-target\";i:1;s:11:\"css-classes\";i:2;s:3:\"xfn\";i:3;s:11:\"description\";i:4;s:15:\"title-attribute\";}');
INSERT INTO `one_page_wpusermeta` VALUES('23', '1', 'metaboxhidden_nav-menus', 'a:3:{i:0;s:18:\"mega_menu_meta_box\";i:1;s:12:\"add-post_tag\";i:2;s:15:\"add-post_format\";}');
INSERT INTO `one_page_wpusermeta` VALUES('24', '1', 'closedpostboxes_dashboard', 'a:6:{i:0;s:20:\"e-dashboard-overview\";i:1;s:21:\"dashboard_site_health\";i:2;s:19:\"dashboard_right_now\";i:3;s:18:\"dashboard_activity\";i:4;s:21:\"dashboard_quick_press\";i:5;s:17:\"dashboard_primary\";}');
INSERT INTO `one_page_wpusermeta` VALUES('25', '1', 'metaboxhidden_dashboard', 'a:0:{}');
INSERT INTO `one_page_wpusermeta` VALUES('26', '1', 'elementor_introduction', 'a:2:{s:10:\"rightClick\";b:1;s:19:\"colorPickerDropping\";b:1;}');
INSERT INTO `one_page_wpusermeta` VALUES('28', '1', 'wpforms_dismissed', 'a:1:{s:15:\"lite-notice-bar\";i:1589183459;}');
INSERT INTO `one_page_wpusermeta` VALUES('29', '1', 'astra-theme-rating', 'notice-dismissed');
INSERT INTO `one_page_wpusermeta` VALUES('31', '1', 'session_tokens', 'a:2:{s:64:\"f3094d3e2fd18e74955b05c3b7c498725a7e3289ae5a929fcf91939423901643\";a:4:{s:10:\"expiration\";i:1589900894;s:2:\"ip\";s:3:\"::1\";s:2:\"ua\";s:115:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36\";s:5:\"login\";i:1589728094;}s:64:\"04ec1c17685ed136cdab47f33073ec12beff72378b220e97f28dc8753fbd3c0d\";a:4:{s:10:\"expiration\";i:1589945942;s:2:\"ip\";s:3:\"::1\";s:2:\"ua\";s:115:\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36\";s:5:\"login\";i:1589773142;}}');
INSERT INTO `one_page_wpusermeta` VALUES('32', '1', 'elementor_admin_notices', 'a:1:{s:11:\"cf7_promote\";s:4:\"true\";}');
/*!40000 ALTER TABLE `one_page_wpusermeta` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
