CREATE TABLE `one_page_wpterm_relationships` (  `object_id` bigint(20) unsigned NOT NULL DEFAULT 0,  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT 0,  `term_order` int(11) NOT NULL DEFAULT 0,  PRIMARY KEY (`object_id`,`term_taxonomy_id`),  KEY `term_taxonomy_id` (`term_taxonomy_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `one_page_wpterm_relationships` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `one_page_wpterm_relationships` VALUES('61', '2', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('65', '3', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('66', '3', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('67', '3', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('68', '3', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('69', '3', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('70', '4', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('71', '4', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('72', '4', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('73', '4', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('132', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('279', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('285', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('337', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('338', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('339', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('371', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('372', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('373', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('501', '5', '0');
INSERT INTO `one_page_wpterm_relationships` VALUES('502', '5', '0');
/*!40000 ALTER TABLE `one_page_wpterm_relationships` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
