CREATE TABLE `one_page_wpterms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT 0,  PRIMARY KEY (`term_id`),  KEY `slug` (`slug`(191)),  KEY `name` (`name`(191))) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40000 ALTER TABLE `one_page_wpterms` DISABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;
INSERT INTO `one_page_wpterms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `one_page_wpterms` VALUES('2', 'Top Menu', 'top-menu', '0');
INSERT INTO `one_page_wpterms` VALUES('3', 'Social Links Menu', 'social-links-menu', '0');
INSERT INTO `one_page_wpterms` VALUES('4', 'Social Links Menu (2)', 'social-links-menu-2', '0');
INSERT INTO `one_page_wpterms` VALUES('5', 'Top Navigation', 'top-navigation', '0');
/*!40000 ALTER TABLE `one_page_wpterms` ENABLE KEYS */;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
